# Generated by Django 5.2.6 on 2025-11-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': [('can_view_book', 'Can view book'), ('can_create_book', 'Can create book'), ('can_edit_book', 'Can edit book'), ('can_delete_book', 'Can delete book'), ('can_publish_book', 'Can publish book'), ('can_manage_authors', 'Can manage authors')],
            },
        ),
    ]
