"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment-based configuration
# Use environment variables to determine deployment mode
ENVIRONMENT = os.getenv('ENVIRONMENT', 'development').lower()
IS_PRODUCTION = ENVIRONMENT == 'production'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*ar3dr517a40accw@x5+6w@&sz2!bia=a477a9z6ho75+js8%s'

# SECURITY WARNING: don't run with debug turned on in production!
# Set DEBUG to False in production to hide sensitive information and disable the debug toolbar
DEBUG = not IS_PRODUCTION  # Automatically set based on environment

# Configure allowed hosts for production. In production, specify the domain(s) where the app is hosted
ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'example.com', 'www.example.com', 'testserver']  # Update with your production domain



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app',
    'accounts'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Note: django-csp middleware can be added here for more granular CSP control
    # Install: pip install django-csp
    # Then uncomment: 'csp.middleware.CSPMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'bookshelf.CustomUser'

# =====================================================
# SECURITY SETTINGS - HTTPS and Secure Configuration
# =====================================================

# Step 1: HTTPS and SSL/TLS REDIRECT SETTINGS
# These settings enforce HTTPS connections and implement security headers
# Production-ready HTTPS configuration

# Redirect all HTTP requests to HTTPS in production
SECURE_SSL_REDIRECT = IS_PRODUCTION  # True in production, False in development

# HTTP Strict-Transport-Security (HSTS)
# Instructs browsers to only access the site via HTTPS for a specified duration
SECURE_HSTS_SECONDS = 31536000 if IS_PRODUCTION else 0  # 1 year in production, 0 in development
SECURE_HSTS_INCLUDE_SUBDOMAINS = IS_PRODUCTION  # True in production
SECURE_HSTS_PRELOAD = IS_PRODUCTION  # True in production to allow HSTS preload list inclusion

# Step 2: SECURE COOKIE SETTINGS
# Ensures cookies are only sent over HTTPS connections

# Session cookies - only sent over HTTPS
SESSION_COOKIE_SECURE = IS_PRODUCTION  # True in production (requires HTTPS)
SESSION_COOKIE_HTTPONLY = True  # Prevents JavaScript access to session cookies
SESSION_COOKIE_AGE = 3600  # Session expires after 1 hour (3600 seconds)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Session expires when browser is closed

# CSRF cookies - only sent over HTTPS
CSRF_COOKIE_SECURE = IS_PRODUCTION  # True in production (requires HTTPS)
CSRF_COOKIE_HTTPONLY = True  # Prevents JavaScript access to CSRF token
CSRF_COOKIE_AGE = 31449600  # CSRF cookie expires after 1 year
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'https://localhost:8000',
    'https://127.0.0.1:8000',
    'https://example.com',
    'https://www.example.com',
]  # Update with your production domains

# Step 3: SECURE BROWSER HEADERS
# Additional HTTP headers to protect against various attacks

# X-Frame-Options: Prevents clickjacking by blocking embedding in iframes
X_FRAME_OPTIONS = 'DENY'

# Prevents MIME type sniffing (browsers respect Content-Type header)
SECURE_CONTENT_TYPE_NOSNIFF = True

# Enables browser's built-in XSS protection
SECURE_BROWSER_XSS_FILTER = True

# Referrer-Policy: Controls how much referrer information is shared
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Content-Security-Policy header configuration
SECURE_CONTENT_SECURITY_POLICY = {
    'default-src': ("'self'",),
    'script-src': ("'self'", "'unsafe-inline'"),
    'style-src': ("'self'", "'unsafe-inline'"),
    'img-src': ("'self'", "data:", "https:"),
    'font-src': ("'self'",),
    'connect-src': ("'self'",),
    'frame-ancestors': ("'none'",),
    'base-uri': ("'self'",),
}

# Step 4: ADDITIONAL SECURITY SETTINGS

# Prevent caching of sensitive pages
# Set cache-control headers to prevent storing sensitive data in browser cache
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if IS_PRODUCTION else None

# Secure password hashing algorithm
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 12}  # Require at least 12 characters
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# CORS configuration for API access (if needed)
CORS_ALLOWED_ORIGINS = [
    'https://example.com',
    'https://www.example.com',
] if IS_PRODUCTION else []

# Logging configuration for security events
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'security.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django.security': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
