# Generated by Django 5.2.6 on 2025-11-15 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view_book', 'Can view book'), ('can_create_book', 'Can create book'), ('can_edit_book', 'Can edit book'), ('can_delete_book', 'Can delete book'), ('can_publish_book', 'Can publish book'), ('can_manage_authors', 'Can manage authors')]},
        ),
    ]
